sudo: required
language: generic
services:
 - docker
 
before_install:
 - docker build -t yanar/nagios .

script:
 - docker run yanar/nagios /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios4.cfg